package com.alexastudillo.geographicreference.api.openapi;

import org.eclipse.microprofile.openapi.OASFactory;
import org.eclipse.microprofile.openapi.OASFilter;
import org.eclipse.microprofile.openapi.models.Operation;
import org.eclipse.microprofile.openapi.models.OpenAPI;
import org.eclipse.microprofile.openapi.models.headers.Header;
import org.eclipse.microprofile.openapi.models.media.Schema;
import org.eclipse.microprofile.openapi.models.parameters.Parameter;

import java.util.List;

import static com.alexastudillo.geographicreference.api.logging.MDCRequestFilter.COMPANY_ID_HEADER;
import static com.alexastudillo.geographicreference.api.logging.MDCRequestFilter.PROCESS_ID_HEADER;
import static com.alexastudillo.geographicreference.api.logging.MDCRequestFilter.USER_ID_HEADER;

/**
 * Adds the request-correlation contract enforced by {@code MDCRequestFilter} to every API
 * operation.
 */
public final class OpenApiContractFilter implements OASFilter {

    private static final String PROCESS_ID_EXAMPLE = "61c55f47-e889-4a34-b61d-07bb060ab496";
    private static final String COMPANY_ID_EXAMPLE = "51cb989a-8ea5-44e8-b513-1ad36892564b";

    @Override
    public void filterOpenAPI(final OpenAPI openAPI) {
        openAPI.getPaths().getPathItems().values().stream()
                .flatMap(pathItem -> pathItem.getOperations().values().stream())
                .forEach(this::completeOperation);
    }

    private void completeOperation(final Operation operation) {
        operation.addParameter(processIdParameter());
        operation.addParameter(userIdParameter());
        operation.addParameter(companyIdParameter());
        operation.getResponses().getAPIResponses().values()
                .forEach(response -> response.addHeader(PROCESS_ID_HEADER, processIdResponseHeader()));
    }

    private Parameter processIdParameter() {
        return OASFactory.createParameter()
                .name(PROCESS_ID_HEADER)
                .in(Parameter.In.HEADER)
                .description("Optional canonical UUID used to correlate the request. Generated when omitted.")
                .required(false)
                .schema(uuidSchema(PROCESS_ID_EXAMPLE));
    }

    private Parameter userIdParameter() {
        return OASFactory.createParameter()
                .name(USER_ID_HEADER)
                .in(Parameter.In.HEADER)
                .description("Required non-blank caller identifier with a maximum length of 128 characters.")
                .required(true)
                .schema(OASFactory.createSchema()
                        .addType(Schema.SchemaType.STRING)
                        .minLength(1)
                        .maxLength(128)
                        .examples(List.of("api-client")));
    }

    private Parameter companyIdParameter() {
        return OASFactory.createParameter()
                .name(COMPANY_ID_HEADER)
                .in(Parameter.In.HEADER)
                .description("Optional canonical UUID identifying the caller's company.")
                .required(false)
                .schema(uuidSchema(COMPANY_ID_EXAMPLE));
    }

    private Header processIdResponseHeader() {
        return OASFactory.createHeader()
                .description("Effective request-correlation UUID supplied by the caller or generated by the service.")
                .schema(uuidSchema(PROCESS_ID_EXAMPLE));
    }

    private Schema uuidSchema(final String example) {
        return OASFactory.createSchema()
                .addType(Schema.SchemaType.STRING)
                .format("uuid")
                .examples(List.of(example));
    }
}
